---
# tasks file for pSSID

- name: Install perfSONAR additional packages
  debug:
    msg: I'm the pSSID installer!
    
- name: Install system updates
  apt:
    upgrade: dist
  ignore_errors: True
  when: pssid_update_os

- name: install pip
  apt:
    name: python3-pip

- name: install wireless-tools
  apt:
    name: wireless-tools

- name: install macaddress changer
  apt:
    name: macchanger

- name: install python-setuptools
  apt:
    name: python-setuptools

- name: Python3 dependencies
  pip:
    executable: /usr/bin/pip3
    name:
     - python-daemon
     - pika
     - wifi
     - ansible

- name: Remove pSSID directory if exists
  ansible.builtin.file:
    path: "{{ pssid_destination }}"
    state: absent
  ignore_errors: True


- name: clone pSSID repository
  git:
    repo: "{{ pssid_repository }}"
    dest: "{{ pssid_destination }}"
    
- name: Create and Change file ownership of pSSID log file
  file:
    path: /var/log/pSSID
    state: touch
    owner: syslog
    group: adm


- name: Edit rsyslog default config.
  lineinfile:
    path: /etc/rsyslog.d/50-default.conf
    line: local3.*    -/var/log/pSSID


- name: restart rsyslog
  systemd:
    state: restarted
    name: rsyslog
