---
# tasks file for pSSID

- name: Install perfSONAR additional packages
  debug:
    msg: I'm the pSSID installer!
    
- name: Install system updates
  apt:
    upgrade: dist
    update_cache: yes
  ignore_errors: True

- name: install pip
  apt:
    name: python3-pip
    update_cache: yes

- name: install wireless-tools
  apt:
    name: wireless-tools

- name: install macaddress changer
  apt:
    name: macchanger

- name: install python-setuptools
  apt:
    name: python-setuptools

- name: Python3 dependencies
  pip:
    executable: /usr/bin/pip3
    name:
     - python-daemon
     - pika
     - wifi
     - ansible

- name: Remove pSSID directory if exists
  ansible.builtin.file:
    path: /usr/local/bin/pssid
    state: absent
  ignore_errors: True


- name: clone pSSID repository
  git: >
    repo=https://github.com/UMNET-perfSONAR/pSSID.git
    dest=/usr/local/bin/pssid
    
    
- name: Create and Change file ownership of pSSID log file
  file:
    path: /var/log/pSSID
    state: touch
    owner: syslog
    group: adm


- name: Edit rsyslog default config.
  lineinfile:
    path: /etc/rsyslog.d/50-default.conf
    line: local3.*    -/var/log/pSSID


- name: restart rsyslog
  systemd:
    state: restarted
    name: rsyslog
